spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/flowerapp
spring.datasource.username=root
spring.datasource.password=defg5678@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.data.mongodb.uri=mongodb+srv://nvnprabakar:QKSf3IPpfdMK0lAh@cluster0.4f3hm.mongodb.net/?appName=Cluster0
graph.api.base-url=http://localhost:5000/api/graph
